### ISSUE TITLE
keyIndex out of value length

### ISSUE THREAD

**Issue by michaelwp** [michaelwp/obj-group#5]
if keyIndex out of value length it's grouping with undefined key

**Comment by thebishaldeb** [comment]
Want to work on it. Provide some details please.

**Comment by michaelwp** [comment]
if the keyIndex out of the value length the result be like this :

{
  undefined: [
    [ 'sniper', 'agility', 'ranged' ],
    [ 'axe', 'strength', 'melee' ],
    [ 'tusk', 'strength', 'melee' ],
    [ 'crystal maiden', 'intelligence', 'ranged' ],
    [ 'phantom assasin', 'agility', 'melee' ],
    [ 'windrunner', 'intelligence', 'ranged' ]
  ]

You can create a limit if the keyIndex exceeds the length of the value it will not produce a result but a warning.
or maybe you have other idea

**Comment by kgoel085** [comment]
@michaelwp  i will like to solve this but i have a question can i change the code structure as i think using a for loop is better for this situation rather than forEach

**Comment by kgoel085** [comment]
![image](https://user-images.githubusercontent.com/38721303/67162930-f8fce000-f386-11e9-9aef-387820ae98a2.png)

this is my suggestion and sorry if i m doing this wrong i m new to this contribution thing on github just starting @michaelwp

**Comment by michaelwp** [comment]
Nice.. I will review this... btw thank u

**Comment by kgoel085** [comment]
@michaelwp sure thank you

**Comment by michaelwp** [comment]
pls fork then create pull request bro
