### ISSUE TITLE
if the value item array length === 2 (see the description)

### ISSUE THREAD

**Issue by michaelwp** [michaelwp/obj-group#6]
const value = [
    ['sniper', 'agility'],
    ['axe', 'strength'],
    ['tusk', 'strength'],
    ['crystal maiden', 'intelligence'],
    ['phantom assasin', 'agility'],
    ['windrunner', 'intelligence']
];

result : 

change from :
{
  agility: [ [ 'sniper' ], [ 'phantom assasin' ] ],
  strength: [ [ 'axe' ], [ 'tusk' ] ],
  intelligence: [ [ 'crystal maiden' ], [ 'windrunner' ] ]
}
to :
{
  agility: [ 'sniper' ,  'phantom assasin' ],
  strength: [ 'axe' , 'tusk' ],
  intelligence: [  'crystal maiden' ,  'windrunner' ] 
}

**Comment by thesanjeevsharma** [comment]
I would like to take this issue. Please assign.

**Comment by michaelwp** [comment]
> I would like to take this issue. Please assign

fork the project, clone then create pull request
